# Generated by Django 3.0.5 on 2020-04-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name="Nom de l'entreprise")),
                ('director', models.CharField(default='Mr/Mme', max_length=30, verbose_name='Directeur Général')),
                ('domaine', models.CharField(max_length=50, verbose_name="Domaine d'activité")),
                ('contact', models.CharField(default='+225 00 00 00 00', max_length=50, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('link', models.URLField(default='https://', unique=True, verbose_name='Site internet')),
                ('location', models.CharField(max_length=50, verbose_name='Lieu')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
