# Generated by Django 3.0.5 on 2020-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='link',
            field=models.URLField(blank=True, default='https://', unique=True, verbose_name='Site internet'),
        ),
    ]
